language: node_js
node_js:
  - "node"

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

cache: npm

script: ./scripts/deploy.sh

